name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: 'Backend Dependencies'
        run: npm i
      - name: 'Frontend Dependencies & Build'
        run: cd frontend && npm i && npm run build
      - name: 'Create .env file'
        run: cd backend && echo "${{ secrets.ENV_PROD }}" > .env
      - name: 'Deploy'
        run: pm2 stop 1 && pm2 start 1 && sudo service nginx restart
