name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: 
          npm i 
      - name: 'Create env file'
        run: |
          echo "${{ secrets.Production }}" > .env
      - name: 'frontend'
        run:
          cd frontend
          npm i 
          npm run build 
