name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Build
      - run: npm i
          cd frontend
          npm i
          npm run build
          pm2 stop 0
          pm2 start 0
          pm2 save
